
version: '3.8'

services:
  backend:
    build: ./server
    container_name: 6uos_backend
    ports:
      - "3000:3000"
    volumes:
      - ./mnt/library:/mnt/library
      - ./server/database.sqlite:/usr/src/app/database.sqlite
    environment:
      - LIBRARY_PATH=/mnt/library
      - DB_PATH=/usr/src/app/database.sqlite
    restart: unless-stopped

  frontend:
    build: .
    container_name: 6uos_frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped
